TIGHTENING_TEST_TYPE = "tightening"
PROM_TIGHTENING_TEST_TYPE = "promiscuous_tightening"

ALL_TIGHTENING_TEST_TYPE_LIST = [TIGHTENING_TEST_TYPE, PROM_TIGHTENING_TEST_TYPE]

MEASURE_TYPE = "measure"
MULTI_MEASURE_TYPE = "multi_measure"
PASS_FAIL_TYPE = "pass_fail"


ALL_MEASURE_TYPE_LIST = [MEASURE_TYPE, MULTI_MEASURE_TYPE, PASS_FAIL_TYPE]